nome = str(input('Digite o nome do cliente: '))
dia = int(input('Digite o dia de vencimento: '))
mês = str(input('Digite o mês de vencimento: '))
valor = str(input('Digite o valor da fatura: '))
print('Olá', nome)
print('A sua fatura com vencimento em',dia, 'de', mês,'no valor de',valor,'está fechada.')